load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_binary(
    name = "zero-to-nix-go",
    srcs = ["cmd/zero-to-nix-go/main.go"],
    importpath = "your/module/path/cmd/zero-to-nix-go",
    visibility = ["//visibility:public"],
)